name: workflow
on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: Multiline Commands
        run: |
          node -v
          npm -v

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View Software Version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
      - name: echo
        run: Write-Output "Windows String"
      - name: Error Step
        run: doesnotexist!
